server:
  port: 8887
spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/lmonkiewicz/config-example"
          search-paths:
            - 'config/{application}/'
          default-label: 'main'
